解析命令行输入
MrChenWithCapsule/yajhttp pull request #2
Opened 2021-05-07 08:28 UTC by cn-zheshi

2021-05-07 08:37 UTC, MrChenWithCapsule requested changes
加点注释？

2021-05-07 08:37 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +    public void parse(String[] args) throws FileNotFoundException {
这里为什么有一个 FileNotFoundException?

2021-05-07 08:37 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +    boolean ish = false;
这是啥？

2021-05-07 08:38 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +    boolean ish = false;
(ish

2021-05-07 08:45 UTC, cn-zheshi commented on src/main/java/nju/yajhttp/Client.java
> +    public void parse(String[] args) throws FileNotFoundException {
需要输出到文件的话，后面跟个path如果不存在我不会去创建

2021-05-07 08:45 UTC, cn-zheshi commented on src/main/java/nju/yajhttp/Client.java
> +    boolean ish = false;
有没有-h

2021-05-07 08:46 UTC, cn-zheshi commented on src/main/java/nju/yajhttp/Client.java
> +    public void parse(String[] args) throws FileNotFoundException {
我选择直接告诉用户文件不存在

2021-05-07 08:48 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +    public void parse(String[] args) throws FileNotFoundException {
考虑你想要用这东西下载文件的情况，为什么你下载一个文件之前还有手动创建那个文件？

2021-05-07 08:49 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +    public void parse(String[] args) throws FileNotFoundException {
我觉得应该没有的话就创建文件。

2021-05-07 08:50 UTC, cn-zheshi commented on src/main/java/nju/yajhttp/Client.java
> +    boolean ish = false;
不过-h我不知道应该输出啥所以没做后续处理（

2021-05-07 08:50 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +                    header.put("authorization", tempstr);
authorization 应该首字母大写。

2021-05-07 08:50 UTC, cn-zheshi commented on src/main/java/nju/yajhttp/Client.java
> +    public void parse(String[] args) throws FileNotFoundException {
OK，我去改一下

2021-05-07 08:51 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +                    header.put("content-type", "application/x-www-form-urlencoded");
content-type 首字母大写。

2021-05-07 08:51 UTC, cn-zheshi commented on src/main/java/nju/yajhttp/Client.java
> +                    header.put("authorization", tempstr);
好

2021-05-07 08:53 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +                port = 8000;
http 的默认 port 是 80。uri 有一个 port() 方法，在用户指定了端口的时候应该用这个。

2021-05-07 08:56 UTC, MrChenWithCapsule commented on src/main/java/nju/yajhttp/Client.java
> +    boolean ish = false;
就输出帮助信息然后退出。

2021-05-07 09:23 UTC, MrChenWithCapsule commented
![image](https://user-images.githubusercontent.com/30191901/117428715-e80bc380-af58-11eb-9cf4-5e500c5fa3ba.png)
没指定 port 的时候会报错。

2021-05-07 09:39 UTC, MrChenWithCapsule commented
![image](https://user-images.githubusercontent.com/30191901/117430844-1c807f00-af5b-11eb-8d23-015cf380b3cf.png)
下载图片的时候有bug。

2021-05-07 09:42 UTC, MrChenWithCapsule commented
> ![image](https://user-images.githubusercontent.com/30191901/117430844-1c807f00-af5b-11eb-8d23-015cf380b3cf.png)
> 下载图片的时候有bug。

你可以和 curl 比较一下输出的文件有什么差别。

2021-05-08 07:41 UTC, MrChenWithCapsule approved these changes

2021-05-08 07:41 UTC, merged